# Site settings
title: Journal of Simon Eames
email: simon.richard.eames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll" # the subpath of your site, e.g. /blog/
url: "https://sreal.github.io" # the base hostname & protocol for your site
twitter_username: sreal
github_username:  sreal

# Build settings
markdown: kramdown
