# Site settings
title: Journal of Simon Eames
email: simon.richard.eames@gmail.com
description: I build stuff and help others build things. Usually with computers.
baseurl: "/jekyll"
url: "https://sreal.github.io"
twitter_username: sreal
github_username:  sreal

# Build settings
markdown: kramdown
